postgres-plugin/challenges

lib/fixtures/challenges-table.sql
=> swap column order to match table name order closes #5

lib/formatters/getChallengeById.js, lib/formatters/index.js, lib/index.js, lib/queries/getChallenge.js, tests/getChallenge.test.js, tests/setup.test.js
Closes #19
Formats the data received from the database, to output a single object, which includes the tags associated with the challenge.
=> Format getChallengeById object

README.md
updates the description so that it specifies what we put in, and what we get back out of the getChallenge function
=> updates README with getChallenge functionality

example/server.js, lib/helpers/init-pg-challenges.js, lib/index.js, package.json, tests/setup/initialise-pg-challenges.test.js
Alter plugin so that it registers `.pg.challenge` on the request object.
closes #33
=> add .pg.challenges to the request object.

README.md, lib/formatters/getById.js, tests/add/endpoint.test.js, tests/getByTag/endpoint.test.js
Resolves #37 
Also temporary solution to #40
=> Documentation

lib/index.js, package.json
=> update plugin to use new query function

README.md, example/server.js, lib/index.js, lib/queries/checkEditable.js, lib/queries/index.js, package.json, tests/checkEditable/endpoint.test.js
issue is here: https://github.com/emfoundation/ce100-app/issues/441
add check editable function
=> add check editable function

README.md, lib/queries/add.js, package.json, tests/add/endpoint.test.js, tests/add/query.test.js
Closes #50 
Changes .add query so that the ID (created by SERIAL in postgres) is returned upon inserting into the table
=> Changes '.add' query so id returned

lib/index.js, lib/queries/getAllActive.js, package.json, tests/getAllActive/endpoint.test.js, tests/getByTag/endpoint.test.js
Closes #49 
Fixes .getAllActive query so that it returns all active tags - regardless of whether a tag has been attached
=> fixes getAllActive query

README.md, lib/formatters/getByTag.js, package.json, tests/getByTag/formatter.test.js
Closes #53 
Adds a ternary prior to formatting the tags in the way that it should otherwise be.
=> Adds a ternary to check what should be returned

README.md, example/data/challenges.json, example/server.js, lib/formatters/getById.js, lib/queries/getById.js, package.json, tests/add/endpoint.test.js, tests/getById/endpoint.test.js, tests/getById/query.test.js
Closes #57 
Fixes query so that id is returned if chal is active and org is active, with or without tags.
Updates challenges.json with two new challenges.
Updates tests
=> Fix get by id query

lib/queries/checkEditable.js, package.json
=> check editable for primary user

README.md, example/server.js, lib/index.js, lib/queries/getArchived.js, lib/queries/index.js, package.json, tests/getArchived/endpoint.test.js
archived challenges for an org https://github.com/emfoundation/ce100-app/issues/268
=> add archived challenges for specific org

lib/queries/getByTag.js, package.json, tests/getByTag/endpoint.test.js, tests/getByTag/query.test.js
see https://github.com/emfoundation/ce100-app/issues/615
fixes issue where inactive challenge was being returned. Updates tests.
=> updates tests and fixes inactive chal query bug

lib/fixtures/create-tables.sql, package.json
ref: https://github.com/emfoundation/ce100-app/issues/884
=> update type of title to varchar

example/server.js, lib/index.js, lib/queries/index.js, lib/queries/search.js, package.json, tests/search/endpoint.test.js
ref: https://github.com/emfoundation/ce100-app/issues/928
=> search for challenges

lib/queries/search.js, package.json, tests/search/endpoint.test.js
This PR add brackets around conditions on the where clause of the query
=> make sure to return only active challenges

example/server.js, lib/index.js, lib/queries/getByOrgId.js, lib/queries/index.js, package.json, tests/getByOrgId/endpoint.test.js
Return all the active challenges linked to an organisation
=> get active challenges of an organisation

.gitignore, config/load-config.js, example/server.js, example/start.js, lib/formatters/getMatchingChallenges.js, lib/formatters/index.js, lib/index.js, lib/queries/getMatchingChallenges.js, lib/queries/index.js, package.json, tests/getMatchingChallenges/endpoint.test.js
ref: https://github.com/emfoundation/ce100-app/issues/16
matches challenges together and return a list of challenges sorted by the most challege matches
=> Match challenges

lib/queries/getComments.js, package.json
Return ```author_id``` when getting the comments of  a challenge
=> return author id with the comment query

lib/queries/getComments.js, package.json
add in the search query the "flagged" column/property of the comment
=> return flagged property of the comment

lib/queries/getComments.js, package.json
merge after #79 
return ```author_flag```
=> return author_flag property of the comment

example/server.js, lib/index.js, lib/queries/flagComment.js, lib/queries/getComments.js, lib/queries/index.js, package.json, tests/flagComment/endpoint.test.js
update the property flagged to true and add the author_flag id
=> Flag comment

example/server.js, lib/formatters/getMatchingChallenges.js, lib/index.js, lib/queries/getMatchingChallenges.js, package.json
ref: https://github.com/emfoundation/ce100-app/issues/16#issuecomment-338697964
=> Match other challenges

example/server.js, lib/index.js, lib/queries/getComment.js, lib/queries/index.js, package.json, tests/getComment/endpoint.test.js
=> Get comment

example/server.js, lib/index.js, lib/queries/getCommentInfo.js, lib/queries/index.js, package.json, tests/getCommentInfo/endpoint.test.js
get the main data linked to a comment: org, challenge, people
=> get information  of a flagged comment

example/server.js, lib/index.js, lib/queries/search.js, package.json, tests/search/endpoint.test.js
If tags or locations are passed to search, performs a union with getByTagsAndLocations query
=> uses tags/locations for search

lib/index.js, lib/queries/getOwnerChallenge.js, lib/queries/index.js, package.json
Return the user who created a challenge
=> get owner of a challenge

lib/queries/getMatchingOrgs.js, package.json
the matches organisation return the logo
=> return org logo for matches

lib/queries/getUsersArchived.js, package.json
rename id and title to chal_id and chal_title for consistency with the other ```getUsersChallenges``` query
=> update get archive challenge query

lib/formatters/getMatchingOrgs.js, lib/queries/getMatchingOrgs.js, package.json, tests/getMatchingOrgs/endpoint.test.js
use org_name, org_id org_logo_url instead of just name id and logo_url to keep consistency with the application
=> update name property for matching orgs

lib/queries/getComments.js, package.json
return the user type of the comment's author
=> return the user type for the comments authors

lib/queries/getComment.js, package.json
the ```getComment``` return the user type of the author of the comment (similar to #94 )
=> get user type with getComment

lib/queries/getByTagsAndLocations.js, package.json
get challenges order by date and title name
=> order challenges list

example/server.js, lib/index.js, lib/queries/challengeEditable.js, lib/queries/index.js, package.json, tests/challengeEditable/endpoint.test.js
add endpoint ```challengeEditable``` which takes the challenge id and the user id and return true/false if hte challenge belongs to the user
=> check if challenge is editable

lib/queries/search.js, package.json
Return creator_active linked to challenges on search query
=> add people active on search challenge

lib/queries/getById.js, package.json, tests/getById/endpoint.test.js
return getById challenges or active and inactive orgs
=> return challenges of inactive org

example/server.js, lib/fixtures/create-tables.sql, lib/index.js, lib/queries/deleteChallenge.js, lib/queries/index.js, package-lock.json, package.json, tests/delete/endpoint.test.js
adds delete challenge query 
I've left comments where changes to the code have _actually_ been made - the rest is just linting issues
=> adds delete challenge query
